# Generated by Django 5.1.7 on 2025-06-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explication',
            field=models.TextField(blank=True, help_text='Explication de la question', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ordre',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
