# Generated by Django 5.2.1 on 2025-06-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0003_question_explication_question_ordre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='nombre_utilisations',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Nombre de fois que cette question a été utilisée'
            ),
        ),
    ]
