# Generated by Django 5.2.1 on 2025-06-30 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0004_add_nombre_utilisations_to_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
