# Generated by Django 5.2.1 on 2025-06-30 12:30

from django.db import migrations, models


def add_explication_field_if_not_exists(apps, schema_editor):
    """Ajoute le champ explication s'il n'existe pas déjà"""
    db_alias = schema_editor.connection.alias
    
    # Vérifier si la colonne existe déjà
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'celica_web_reponse' 
            AND COLUMN_NAME = 'explication'
        """)
        column_exists = cursor.fetchone()[0] > 0
        
        if not column_exists:
            # Ajouter la colonne
            cursor.execute("""
                ALTER TABLE celica_web_reponse 
                ADD COLUMN explication LONGTEXT
            """)
            print("✅ Colonne 'explication' ajoutée à la table celica_web_reponse")
        else:
            print("ℹ️ Colonne 'explication' existe déjà dans la table celica_web_reponse")


def remove_explication_field(apps, schema_editor):
    """Supprime le champ explication (pour le rollback)"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE celica_web_reponse 
            DROP COLUMN IF EXISTS explication
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0005_fix_date_creation_field'),
    ]

    operations = [
        migrations.RunPython(
            add_explication_field_if_not_exists,
            remove_explication_field
        ),
    ]
