# Generated by Django 5.2.1 on 2025-06-30 12:55

from django.db import migrations, models
import django.utils.timezone


def add_date_creation_to_reponse(apps, schema_editor):
    """Ajoute le champ date_creation et copie les données depuis created_at"""
    
    with schema_editor.connection.cursor() as cursor:
        # Vérifier si la colonne date_creation existe déjà
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'celica_web_reponse' 
            AND COLUMN_NAME = 'date_creation'
        """)
        column_exists = cursor.fetchone()[0] > 0
        
        if not column_exists:
            # Ajouter la colonne date_creation
            cursor.execute("""
                ALTER TABLE celica_web_reponse 
                ADD COLUMN date_creation DATETIME(6) DEFAULT NOW(6)
            """)
            
            # Copier les données depuis created_at vers date_creation
            cursor.execute("""
                UPDATE celica_web_reponse 
                SET date_creation = created_at 
                WHERE created_at IS NOT NULL
            """)
            
            print("✅ Colonne 'date_creation' ajoutée à celica_web_reponse et données copiées")
        else:
            print("ℹ️ Colonne 'date_creation' existe déjà dans celica_web_reponse")


def remove_date_creation_from_reponse(apps, schema_editor):
    """Supprime le champ date_creation (pour le rollback)"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE celica_web_reponse 
            DROP COLUMN IF EXISTS date_creation
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0006_fix_reponse_explication_field'),
    ]

    operations = [
        migrations.RunPython(
            add_date_creation_to_reponse,
            remove_date_creation_from_reponse
        ),
    ]
