# Generated by Django 5.2.1 on 2025-06-30 13:10

from django.db import migrations, models


def add_ordre_field_to_reponse(apps, schema_editor):
    """Ajoute le champ ordre à la table celica_web_reponse"""
    
    with schema_editor.connection.cursor() as cursor:
        # Vérifier si la colonne ordre existe déjà
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'celica_web_reponse' 
            AND COLUMN_NAME = 'ordre'
        """)
        column_exists = cursor.fetchone()[0] > 0
        
        if not column_exists:
            # Ajouter la colonne ordre
            cursor.execute("""
                ALTER TABLE celica_web_reponse 
                ADD COLUMN ordre INT(10) UNSIGNED DEFAULT 1
            """)
            print("✅ Colonne 'ordre' ajoutée à celica_web_reponse")
        else:
            print("ℹ️ Colonne 'ordre' existe déjà dans celica_web_reponse")


def remove_ordre_field_from_reponse(apps, schema_editor):
    """Supprime le champ ordre (pour le rollback)"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE celica_web_reponse 
            DROP COLUMN IF EXISTS ordre
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0008_fix_created_at_defaults'),
    ]

    operations = [
        migrations.RunPython(
            add_ordre_field_to_reponse,
            remove_ordre_field_from_reponse
        ),
    ]
