# Generated by Django 5.2.1 on 2025-06-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0012_add_priorite_to_notification'),
    ]

    operations = [
    ]
