# Generated by Django 5.2.1 on 2025-06-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0013_fix_apropos_table'),
    ]

    operations = [
    ]
