# Generated by Django 5.2.1 on 2025-07-01 10:28

from django.db import migrations
from django.core.validators import MinValueValidator, MaxValueValidator
import django.db.models


def add_note_sur_20_if_missing(apps, schema_editor):
    """
    Ajoute la colonne note_sur_20 à la table celica_web_resultat si elle n'existe pas
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Vérifier si la colonne existe déjà
        cursor.execute("""
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'celica_web_resultat'
            AND COLUMN_NAME = 'note_sur_20'
        """)
        
        column_exists = cursor.fetchone()[0] > 0
        
        if not column_exists:
            print("🔧 Ajout de la colonne note_sur_20 à la table celica_web_resultat...")
            cursor.execute("""
                ALTER TABLE celica_web_resultat 
                ADD COLUMN note_sur_20 DOUBLE NULL 
                COMMENT 'Note ramenée sur 20'
            """)
            print("✅ Colonne note_sur_20 ajoutée avec succès")
        else:
            print("✅ La colonne note_sur_20 existe déjà")


def remove_note_sur_20(apps, schema_editor):
    """
    Supprime la colonne note_sur_20 (rollback)
    """
    with schema_editor.connection.cursor() as cursor:
        # Vérifier si la colonne existe avant de la supprimer
        cursor.execute("""
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'celica_web_resultat'
            AND COLUMN_NAME = 'note_sur_20'
        """)
        
        column_exists = cursor.fetchone()[0] > 0
        
        if column_exists:
            print("🔧 Suppression de la colonne note_sur_20...")
            cursor.execute("ALTER TABLE celica_web_resultat DROP COLUMN note_sur_20")
            print("✅ Colonne note_sur_20 supprimée")


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0014_fix_apropos_table'),
    ]

    operations = [
        migrations.RunPython(
            add_note_sur_20_if_missing,
            remove_note_sur_20,
            hints={'verbosity': 2}
        ),
    ]
