# Generated by Django 5.2.1 on 2025-07-01 10:30

from django.db import migrations


def fix_resultat_columns(apps, schema_editor):
    """
    Corrige la structure de la table celica_web_resultat en ajoutant les colonnes manquantes
    """
    with schema_editor.connection.cursor() as cursor:
        print("🔧 Correction de la structure de la table celica_web_resultat...")
        
        # Vérifier et ajouter la colonne commentaires
        cursor.execute("""
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'celica_web_resultat'
            AND COLUMN_NAME = 'commentaires'
        """)
        
        if cursor.fetchone()[0] == 0:
            print("  ➤ Ajout de la colonne 'commentaires'...")
            cursor.execute("""
                ALTER TABLE celica_web_resultat 
                ADD COLUMN commentaires LONGTEXT NULL 
                COMMENT 'Commentaires sur le résultat'
            """)
            print("    ✅ Colonne 'commentaires' ajoutée")
        else:
            print("    ✅ Colonne 'commentaires' existe déjà")
        
        # Vérifier et ajouter la colonne temps_ecoule
        cursor.execute("""
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'celica_web_resultat'
            AND COLUMN_NAME = 'temps_ecoule'
        """)
        
        if cursor.fetchone()[0] == 0:
            print("  ➤ Ajout de la colonne 'temps_ecoule'...")
            cursor.execute("""
                ALTER TABLE celica_web_resultat 
                ADD COLUMN temps_ecoule INT UNSIGNED NULL 
                COMMENT 'Temps écoulé en minutes'
            """)
            print("    ✅ Colonne 'temps_ecoule' ajoutée")
        else:
            print("    ✅ Colonne 'temps_ecoule' existe déjà")
            
        print("✅ Structure de la table celica_web_resultat corrigée")


def reverse_fix_resultat_columns(apps, schema_editor):
    """
    Supprime les colonnes ajoutées (rollback)
    """
    with schema_editor.connection.cursor() as cursor:
        print("🔧 Suppression des colonnes ajoutées...")
        
        # Supprimer commentaires si elle existe
        cursor.execute("""
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'celica_web_resultat'
            AND COLUMN_NAME = 'commentaires'
        """)
        
        if cursor.fetchone()[0] > 0:
            cursor.execute("ALTER TABLE celica_web_resultat DROP COLUMN commentaires")
            print("  ✅ Colonne 'commentaires' supprimée")
        
        # Supprimer temps_ecoule si elle existe
        cursor.execute("""
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'celica_web_resultat'
            AND COLUMN_NAME = 'temps_ecoule'
        """)
        
        if cursor.fetchone()[0] > 0:
            cursor.execute("ALTER TABLE celica_web_resultat DROP COLUMN temps_ecoule")
            print("  ✅ Colonne 'temps_ecoule' supprimée")


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0015_fix_missing_note_sur_20'),
    ]

    operations = [
        migrations.RunPython(
            fix_resultat_columns,
            reverse_fix_resultat_columns,
            hints={'verbosity': 2}
        ),
    ]
