# Generated by Django 5.2.1 on 2025-07-01 12:18

from django.db import migrations
from django.utils import timezone


def fix_aide_table_structure(apps, schema_editor):
    """
    Corrige la structure de la table celica_web_aide pour la faire correspondre au modèle
    """
    with schema_editor.connection.cursor() as cursor:
        print("🔧 Correction de la structure de la table celica_web_aide...")
        
        # 1. Ajouter la colonne mots_cles
        cursor.execute("""
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'celica_web_aide'
            AND COLUMN_NAME = 'mots_cles'
        """)
        
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE celica_web_aide 
                ADD COLUMN mots_cles VARCHAR(200) DEFAULT ''
            """)
            print("✅ Colonne 'mots_cles' ajoutée")
        
        # 2. Ajouter la colonne ordre_affichage
        cursor.execute("""
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'celica_web_aide'
            AND COLUMN_NAME = 'ordre_affichage'
        """)
        
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE celica_web_aide 
                ADD COLUMN ordre_affichage INT UNSIGNED NOT NULL DEFAULT 1
            """)
            print("✅ Colonne 'ordre_affichage' ajoutée")
        
        # 3. Ajouter la colonne visible
        cursor.execute("""
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'celica_web_aide'
            AND COLUMN_NAME = 'visible'
        """)
        
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE celica_web_aide 
                ADD COLUMN visible TINYINT(1) NOT NULL DEFAULT 1
            """)
            print("✅ Colonne 'visible' ajoutée")
        
        # 4. Ajouter la colonne date_creation
        cursor.execute("""
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'celica_web_aide'
            AND COLUMN_NAME = 'date_creation'
        """)
        
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE celica_web_aide 
                ADD COLUMN date_creation DATETIME(6) NOT NULL DEFAULT '{}'
            """.format(timezone.now().strftime('%Y-%m-%d %H:%M:%S.%f')))
            print("✅ Colonne 'date_creation' ajoutée")
        
        # 5. Ajouter la colonne date_modification
        cursor.execute("""
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'celica_web_aide'
            AND COLUMN_NAME = 'date_modification'
        """)
        
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE celica_web_aide 
                ADD COLUMN date_modification DATETIME(6) NOT NULL DEFAULT '{}'
            """.format(timezone.now().strftime('%Y-%m-%d %H:%M:%S.%f')))
            print("✅ Colonne 'date_modification' ajoutée")
        
        # 6. Renommer date_publication en date_creation si nécessaire (migration de données)
        cursor.execute("""
            SELECT COUNT(*)
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'celica_web_aide'
            AND COLUMN_NAME = 'date_publication'
        """)
        
        has_date_publication = cursor.fetchone()[0] > 0
        
        if has_date_publication:
            # Migrer les données de date_publication vers date_creation s'il n'existe pas déjà
            cursor.execute("""
                SELECT COUNT(*)
                FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE()
                AND TABLE_NAME = 'celica_web_aide'
                AND COLUMN_NAME = 'date_creation'
            """)
            
            has_date_creation = cursor.fetchone()[0] > 0
            
            if not has_date_creation:
                cursor.execute("""
                    ALTER TABLE celica_web_aide 
                    CHANGE COLUMN date_publication date_creation DATETIME(6) NOT NULL
                """)
                print("✅ Colonne 'date_publication' renommée en 'date_creation'")
            else:
                # Si date_creation existe déjà, supprimer date_publication
                cursor.execute("""
                    ALTER TABLE celica_web_aide 
                    DROP COLUMN date_publication
                """)
                print("✅ Colonne obsolète 'date_publication' supprimée")
        
        # 7. Modifier la colonne categorie pour correspondre au modèle (VARCHAR(20))
        cursor.execute("""
            ALTER TABLE celica_web_aide 
            MODIFY COLUMN categorie VARCHAR(20) NOT NULL DEFAULT 'general'
        """)
        print("✅ Colonne 'categorie' mise à jour")
        
        print("🎯 Structure de la table celica_web_aide corrigée avec succès!")


def reverse_fix_aide_table_structure(apps, schema_editor):
    """
    Fonction de rollback (optionnelle)
    """
    print("⚠️  Rollback de la correction de structure Aide non implémenté")


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0017_fix_planning_columns'),
    ]

    operations = [
        migrations.RunPython(
            fix_aide_table_structure,
            reverse_fix_aide_table_structure,
        ),
    ]
