# Generated by Django 5.2.1 on 2025-07-01 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0020_fix_statistiques_foreign_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='instructeurs',
            field=models.ManyToManyField(
                blank=True,
                help_text='Instructeurs assignés à ce groupe',
                limit_choices_to={'role': 'instructeur'},
                related_name='groupes_instructeur',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
