# Generated by Django 5.2.1 on 2025-07-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0022_planning_groupes'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='randomize_questions',
            field=models.BooleanField(default=True, help_text="Mélanger l'ordre des questions pour chaque apprenant"),
        ),
    ]
