# Generated by Django 5.2.1 on 2025-07-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0023_test_randomize_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='groupes',
        ),
    ]
