# Generated by Django 5.1.7 on 2025-07-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0024_remove_planning_groupes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='categorie',
            field=models.CharField(choices=[('RSI', 'RSI'), ('ELB', 'ELB'), ('CNS', 'CNS')], max_length=100),
        ),
    ]
