# Generated by Django 5.1.7 on 2025-07-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0025_alter_module_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='categorie',
            field=models.CharField(max_length=100),
        ),
    ]
