# Generated by Django 5.1.7 on 2025-07-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0026_alter_module_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='details_reponses',
            field=models.JSONField(blank=True, help_text="Détails des réponses données par l'apprenant", null=True),
        ),
    ]
