# Generated by Django 4.2.9 on 2024-01-01 00:00

from django.db import migrations, models

def fix_bareme_values(apps, schema_editor):
    """
    Fonction pour mettre à jour les tests existants avec une valeur par défaut de 20
    pour le champ bareme s'il est NULL ou 0
    """
    Test = apps.get_model('celica_web', 'Test')
    
    # Mettre à jour tous les tests qui ont bareme=NULL ou bareme=0
    tests_to_update = Test.objects.filter(bareme__isnull=True) | Test.objects.filter(bareme=0)
    
    for test in tests_to_update:
        test.bareme = 20.0
        test.save()
    
    print(f"Mis à jour {tests_to_update.count()} tests avec bareme=20")

def reverse_fix_bareme_values(apps, schema_editor):
    """
    Fonction pour annuler la migration (optionnel)
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0027_resultat_details_reponses'),
    ]

    operations = [
        # Mettre à jour les enregistrements existants
        migrations.RunPython(fix_bareme_values, reverse_fix_bareme_values),
        
        # Ajouter la valeur par défaut au champ bareme
        migrations.AlterField(
            model_name='test',
            name='bareme',
            field=models.FloatField(default=20, help_text='Barème total du test'),
        ),
    ] 