# Generated by Django 5.1.7 on 2025-07-11 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0028_fix_bareme_default_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation', models.CharField(help_text='Description de la violation', max_length=200)),
                ('violation_type', models.CharField(blank=True, choices=[('copy_paste', 'Copier-coller'), ('keyboard_shortcut', 'Raccourci clavier'), ('right_click', 'Clic droit'), ('print', 'Impression'), ('navigation', 'Navigation externe'), ('dev_tools', 'Outils de développement'), ('tab_switch', "Changement d'onglet"), ('screenshot', "Capture d'écran"), ('fullscreen_exit', 'Sortie plein écran')], max_length=20, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations_securite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Violation de sécurité',
                'verbose_name_plural': 'Violations de sécurité',
                'ordering': ['-timestamp'],
            },
        ),
    ]
