# Generated by Django 5.1.7 on 2025-01-XX XX:XX

from django.db import migrations, models


def update_visitor_users(apps, schema_editor):
    """Convertir les utilisateurs 'visiteur' en 'apprenant'"""
    Utilisateur = apps.get_model('celica_web', 'Utilisateur')
    # Mettre à jour tous les utilisateurs avec le rôle 'visiteur'
    Utilisateur.objects.filter(role='visiteur').update(role='apprenant')


def reverse_update_visitor_users(apps, schema_editor):
    """Revert: convertir les utilisateurs 'apprenant' en 'visiteur' (si nécessaire)"""
    Utilisateur = apps.get_model('celica_web', 'Utilisateur')
    # Cette fonction peut rester vide ou être utilisée pour un rollback si nécessaire
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0033_alter_utilisateur_statut'),
    ]

    operations = [
        # Mettre à jour les utilisateurs existants avant de changer les choix
        migrations.RunPython(update_visitor_users, reverse_update_visitor_users),
        
        # Modifier le champ role pour supprimer le choix 'visiteur'
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Administrateur'),
                    ('instructeur', 'Instructeur'),
                    ('apprenant', 'Apprenant'),
                ],
                default='apprenant',
                max_length=20
            ),
        ),
    ] 