# Generated by Django 5.1.7 on 2025-01-XX XX:XX

from django.db import migrations, models


def update_en_attente_users(apps, schema_editor):
    """Convertir les utilisateurs 'en_attente' en 'actif'"""
    Utilisateur = apps.get_model('celica_web', 'Utilisateur')
    # Mettre à jour tous les utilisateurs avec le statut 'en_attente'
    Utilisateur.objects.filter(statut='en_attente').update(statut='actif')


def reverse_update_en_attente_users(apps, schema_editor):
    """Revert: convertir les utilisateurs 'actif' en 'en_attente' (si nécessaire)"""
    Utilisateur = apps.get_model('celica_web', 'Utilisateur')
    # Cette fonction peut rester vide ou être utilisée pour un rollback si nécessaire
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0034_remove_visiteur_role'),
    ]

    operations = [
        # Mettre à jour les utilisateurs existants avant de changer les choix
        migrations.RunPython(update_en_attente_users, reverse_update_en_attente_users),
        
        # Modifier le champ statut pour supprimer le choix 'en_attente'
        migrations.AlterField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(
                choices=[
                    ('actif', 'Actif'),
                    ('inactif', 'Inactif'),
                    ('suspendu', 'Suspendu'),
                ],
                default='actif',
                max_length=10
            ),
        ),
    ] 