# Generated by Django 5.1.7 on 2025-07-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0035_remove_en_attente_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='date_preinscription',
        ),
    ]
