# Generated by Django 5.1.7 on 2025-07-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celica_web', '0036_remove_utilisateur_date_preinscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='specialite',
            field=models.CharField(choices=[('RSI', 'RSI'), ('CNS', 'CNS'), ('ELB', 'ELB'), ('AUTRE', 'AUTRE')], default='AUTRE', max_length=20),
        ),
    ]
